Fix context in fs.writeFile callback.
Fixes error:

npm http 200 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1366973405680
npm WARN Building the local index for the first time, please be patient
npm http GET https://registry.npmjs.org/-/all

/var/www/node_modules/npm/node_modules/npm-registry-client/lib/get.js:73
    this.log.warn("", "Building the local index for the first time, please be
             ^
TypeError: Cannot call method 'warn' of undefined
    at requestAll_ (/var/www/node_modules/npm/node_modules/npm-registry-client/lib/get.js:73:14)
    at /var/www/node_modules/npm/node_modules/npm-registry-client/lib/get.js:54:30
    at Object.oncomplete (fs.js:107:15)