Use a https schema so the example works
When you try and run the example with the latest version of the lib it throws the following. This PR changes the example to use https, which works.

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: must have a URL that starts with http: or https:
```